### ISSUE TITLE
Refactor: 각종 에러 헨들링

### ISSUE THREAD

**Issue by happycastle114** [sparcs-kaist/taxi-app#26]
# Summary 

각종 에러에 대한 사용자에게 전달할 에러메세지 추가

# Tasks 

- [x] 인터넷이 연결되지 않았을 때
- [x] 서버와의 연결 상태가 좋지 않을 때
- [x] login 502 bad gateway
... 계속 추가 예정
